
aws.secretsmanager.secretId =arn:aws:secretsmanager:eu-central-1:311912734099:secret:rds!db-3db9de14-bdf5-4351-91a6-14f44b2f2050-2nM5xB
spring.redis.host=productcache-tjjwxk.serverless.euc1.cache.amazonaws.com
spring.redis.port=6379
db.url=jdbc:mysql://database-1.cnoq8om68y8o.eu-central-1.rds.amazonaws.com:3306/products


cloud.aws.region.static=eu-central-1
